name: Terraform plan

on:
  push:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Set OCI key
        run: echo "${{ secrets.OCI_PRIVATE_KEY }}" > ./oci_api_key.pem
          
      - name: Terraform Init & plan
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path: ./keys/oci_api_key.pem
        run: |
          terraform init
          if ["${GITHUB_REF#refs/heads/}" = "dev" ]; then
            VAR_FILE="envs/dev/dev.tfvars"
          elif ["${GITHUB_REF#refs/heads/}" = "staging" ]; then
            VAR_FILE="envs/staging/staging.tfvars"
          else
            VAR_FILE="envs/prod/prod.tfvars"
          fi
          terraform plan -var-file=${VAR_FILE}